"""Agregando tabla partida_concepto

Revision ID: 2f4947c9f608
Revises: 3d14f784336b
Create Date: 2020-12-31 17:20:33.886915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4947c9f608'
down_revision = '3d14f784336b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partida', sa.Column('fecha', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partida', 'fecha')
    # ### end Alembic commands ###
