"""add campo descripcion a tabla Tipo cuenta

Revision ID: 460d0cd02e6b
Revises: 9661bfa9c851
Create Date: 2020-12-23 15:03:03.154136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460d0cd02e6b'
down_revision = '9661bfa9c851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_cuenta', sa.Column('descripcion', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipo_cuenta', 'descripcion')
    # ### end Alembic commands ###
