"""iniciando db

Revision ID: 8a35be58ecf3
Revises: 
Create Date: 2020-12-22 20:47:58.765548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a35be58ecf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubro',
    sa.Column('id_rubro', sa.Integer(), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_rubro')
    )
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_rubro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rubro'], ['rubro.id_rubro'], ),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id_empresa'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('empresa')
    op.drop_table('rubro')
    # ### end Alembic commands ###
