"""add cuenta, subcuenta y tipocuenta

Revision ID: 9661bfa9c851
Revises: 975ababe42ee
Create Date: 2020-12-22 23:03:30.946670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9661bfa9c851'
down_revision = '975ababe42ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_cuenta',
    sa.Column('id_tipo_cuenta', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.String(length=25), nullable=False),
    sa.Column('saldo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_cuenta'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cuenta',
    sa.Column('id_cuenta', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('id_tipocuenta', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipocuenta'], ['tipo_cuenta.id_tipo_cuenta'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id_cuenta'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('subcuenta',
    sa.Column('id_subcuenta', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('id_cuenta', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuenta.id_cuenta'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id_subcuenta'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcuenta')
    op.drop_table('cuenta')
    op.drop_table('tipo_cuenta')
    # ### end Alembic commands ###
