"""cambiando ondelete en Empresa

Revision ID: 975ababe42ee
Revises: 8a35be58ecf3
Create Date: 2020-12-22 20:50:29.097736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975ababe42ee'
down_revision = '8a35be58ecf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('empresa_ibfk_1', 'empresa', type_='foreignkey')
    op.create_foreign_key(None, 'empresa', 'rubro', ['id_rubro'], ['id_rubro'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresa', type_='foreignkey')
    op.create_foreign_key('empresa_ibfk_1', 'empresa', 'rubro', ['id_rubro'], ['id_rubro'])
    # ### end Alembic commands ###
