"""Agregando boolean partida concepto

Revision ID: dc3f710bcaef
Revises: 923d825a9f29
Create Date: 2021-01-01 17:35:17.562701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3f710bcaef'
down_revision = '923d825a9f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partida_concepto', sa.Column('cargo_abono', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partida_concepto', 'cargo_abono')
    # ### end Alembic commands ###
