"""Agregando tabla partida

Revision ID: f747da15f31b
Revises: 7a2b0e499268
Create Date: 2020-12-30 19:59:13.103045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f747da15f31b'
down_revision = '7a2b0e499268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partida',
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('valor_debe', sa.Float(), nullable=True),
    sa.Column('valor_haber', sa.Float(), nullable=True),
    sa.Column('id_ldiario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ldiario'], ['empresa.id_empresa'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_partida')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partida')
    # ### end Alembic commands ###
